spring:
  application:
    name: rnr-config-server
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ldeeley/RnRConfigServerRepo"
          default-label: "main"

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true



management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

my:
  greeting: 'this is local'